### ISSUE TITLE
Import Error : Nomudule named win32crypt

### ISSUE THREAD

**Issue by tatdatpham** [pourquoibenoit/WinPirate#2]
I run file chromepasswords.py and got error Import Error : Nomudule named win32crypt ..

```
I:\tool-win\Tools\Chrome>C:\Python27\python.exe chromepasswords.py
Traceback (most recent call last):
  File "chromepasswords.py", line 7, in <module>
    from win32crypt import CryptUnprotectData
ImportError: No module named win32crypt
```

**Comment by pourquoibenoit** [comment]
Yeah that's because you need to get Pywin32 python extension for it to work. Ideally, I'll make it an exe so that won't be a problem

**Comment by pourquoibenoit** [comment]
Also I should mention that I wrote it in python3, and I see you're using python 2.7
